#!/bin/sh

val_DEFAULT=0

val_RANDOM=110
val_MIDDLE=120
val_MEDIAN3=130
val_RANDOM3=140

val_INSERTION=210
val_SHELL=220

val_METHOD1=310
val_METHOD2=320

selection_value ()
{
    case "${1}" in
        default ) echo ${val_DEFAULT} ;;
        random ) echo ${val_RANDOM} ;;
        middle ) echo ${val_MIDDLE} ;;
        median3 ) echo ${val_MEDIAN3} ;;
        random3 ) echo ${val_RANDOM3} ;;
        insertion ) echo ${val_INSERTION} ;;
        shell ) echo ${val_SHELL} ;;
        method1 ) echo ${val_METHOD1} ;;
        method2 ) echo ${val_METHOD2} ;;
    esac
}

tab="	"

echo "# This file is generated by ${0}"

for pivot in default random random3; do
    suffix1="${pivot}"
    suffix2="${pivot}"
    program_root="tests/test-arrays-patterns-stable"
    program="${program_root}-${suffix1}"
    variable="tests_test_arrays_patterns_stable_${suffix2}"
    echo ""
    echo "TESTS += ${program}"
    echo "EXTRA_PROGRAMS += ${program}"
    echo "CLEANFILES += ${program}"
    echo "CLEANFILES += ${program}_tests.c"
    echo "CLEANFILES += ${program}.dats"
    echo "${variable}_SOURCES ="
    echo "${variable}_SOURCES += ${program}_tests.c"
    echo "${variable}_DEPENDENCIES ="
    echo "${variable}_DEPENDENCIES += ${program}.dats"
    echo "${variable}_DEPENDENCIES += libats2-quicksorts.la"
    echo "${variable}_DEPENDENCIES += \$(STABLE_QUICKSORT_HATS)"
    echo "${variable}_CPPFLAGS ="
    echo "${variable}_CPPFLAGS += \$(AM_CPPFLAGS)"
    echo "${variable}_CPPFLAGS += -DATS_MEMALLOC_LIBC"
    echo "${variable}_LDADD ="
    echo "${variable}_LDADD += libats2-quicksorts.la"
    echo "${program}_tests.c: ${program}.dats"
    echo ""
    echo "${program}.dats: GNUmakefile"
    echo "${tab}\$(call v,GEN)" \\
    echo "${tab}printf '%s\n%s\n%s\n%s\n%s\n'"\\
	echo "${tab}${tab}"\''#define PIVOT_METHOD '`selection_value ${pivot}`\' \\
    echo "${tab}${tab}"\''#include '\"${program_root}.common.dats\"\'' > $(@)'
done
