#!/bin/sh

val_DEFAULT=0

val_RANDOM=110
val_MIDDLE=120
val_MEDIAN3=130

val_INSERTION=210
val_SHELL=220

val_METHOD1=310
val_METHOD2=320

selection_value ()
{
    case "${1}" in
        default ) echo ${val_DEFAULT} ;;
        random ) echo ${val_RANDOM} ;;
        middle ) echo ${val_MIDDLE} ;;
        median3 ) echo ${val_MEDIAN3} ;;
        insertion ) echo ${val_INSERTION} ;;
        shell ) echo ${val_SHELL} ;;
        method1 ) echo ${val_METHOD1} ;;
        method2 ) echo ${val_METHOD2} ;;
    esac
}

tab="	"

echo "# This file is generated by ${0}"

for pivot in default random middle median3; do
    for small_sort in default insertion shell; do
        case ${small_sort} in
            default   ) small_size=${val_DEFAULT} ;;
            insertion ) small_size=80 ;;
            shell     ) small_size=350 ;;
        esac
        for partition in default method1 method2; do
            suffix1="${pivot}-${small_sort}-${partition}"
            suffix2="${pivot}_${small_sort}_${partition}"
            program_root="tests/test-arrays-patterns-unstable"
            program="${program_root}-${suffix1}"
            variable="tests_test_arrays_patterns_unstable_${suffix2}"
            echo ""
            echo "TESTS += ${program}"
            echo "EXTRA_PROGRAMS += ${program}"
            echo "CLEANFILES += ${program}"
            echo "CLEANFILES += ${program}_tests.c"
            echo "CLEANFILES += ${program}.dats"
            echo "${variable}_SOURCES ="
            echo "${variable}_SOURCES += ${program}_tests.c"
            echo "${variable}_DEPENDENCIES ="
            echo "${variable}_DEPENDENCIES += ${program}.dats"
            echo "${variable}_DEPENDENCIES += libats2-quicksorts.la"
            echo "${variable}_DEPENDENCIES += \$(UNSTABLE_QUICKSORT_HATS)"
            echo "${variable}_CPPFLAGS ="
            echo "${variable}_CPPFLAGS += \$(AM_CPPFLAGS)"
            echo "${variable}_CPPFLAGS += -DATS_MEMALLOC_LIBC"
            echo "${variable}_LDADD ="
            echo "${variable}_LDADD += libats2-quicksorts.la"
            echo "${program}_tests.c: ${program}.dats"
            echo ""
            echo "${program}.dats: GNUmakefile"
            echo "${tab}\$(call v,GEN)" \\
            echo "${tab}printf '%s\n%s\n%s\n%s\n%s\n'"\\
		    echo "${tab}${tab}"\''#define PIVOT_METHOD '`selection_value ${pivot}`\' \\
		    echo "${tab}${tab}"\''#define SMALL_SORT '`selection_value ${small_sort}`\' \\
		    echo "${tab}${tab}"\''#define SMALL_SIZE '${small_size}\' \\
		    echo "${tab}${tab}"\''#define PARTITION_METHOD '`selection_value ${partition}`\' \\
            echo "${tab}${tab}"\''#include '\"${program_root}.common.dats\"\'' > $(@)'
        done
    done
done
